// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: activity.proto

package com.hk.activity.proto;

public interface ActivityReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:activity.ActivityReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated double amount = 3;</code>
   * @return A list containing the amount.
   */
  java.util.List<java.lang.Double> getAmountList();
  /**
   * <code>repeated double amount = 3;</code>
   * @return The count of amount.
   */
  int getAmountCount();
  /**
   * <code>repeated double amount = 3;</code>
   * @param index The index of the element to return.
   * @return The amount at the given index.
   */
  double getAmount(int index);
}
