// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: activity.proto

package com.hk.activity.proto;

public interface ActivityResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:activity.ActivityRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
