// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: activity.proto

package com.hk.activity.proto;

public final class ActivityProto {
  private ActivityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_activity_ActivityReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_activity_ActivityReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_activity_ActivityRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_activity_ActivityRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016activity.proto\022\010activity\"7\n\013ActivityRe" +
      "q\022\n\n\002id\030\001 \001(\004\022\014\n\004name\030\002 \001(\t\022\016\n\006amount\030\003 " +
      "\003(\001\".\n\013ActivityRes\022\n\n\002id\030\001 \001(\004\022\023\n\013descri" +
      "ption\030\002 \001(\t*\217\001\n\tProtoCode\022\010\n\004NONE\020\000\022\026\n\016F" +
      "IRST_PAGE_REQ\020\200\376\377\377\003\022\026\n\016FIRST_PAGE_RES\020\200\376" +
      "\377\377\007\022\022\n\nREWARD_REQ\020\201\376\377\377\003\022\022\n\nREWARD_RES\020\201\376" +
      "\377\377\007\022\017\n\007BUY_REQ\020\202\376\377\377\003\022\017\n\007BUY_RES\020\202\376\377\377\007B9\n" +
      "\025com.hk.activity.protoB\rActivityProtoP\001\242" +
      "\002\016ACTIVITY_PROTOb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_activity_ActivityReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_activity_ActivityReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_activity_ActivityReq_descriptor,
        new java.lang.String[] { "Id", "Name", "Amount", });
    internal_static_activity_ActivityRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_activity_ActivityRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_activity_ActivityRes_descriptor,
        new java.lang.String[] { "Id", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
