// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: activity.proto

package com.hk.activity.proto;

/**
 * Protobuf enum {@code activity.ProtoCode}
 */
public enum ProtoCode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NONE = 0;</code>
   */
  NONE(0),
  /**
   * <code>FIRST_PAGE_REQ = 1073741568;</code>
   */
  FIRST_PAGE_REQ(1073741568),
  /**
   * <code>FIRST_PAGE_RES = 2147483392;</code>
   */
  FIRST_PAGE_RES(2147483392),
  /**
   * <code>REWARD_REQ = 1073741569;</code>
   */
  REWARD_REQ(1073741569),
  /**
   * <code>REWARD_RES = 2147483393;</code>
   */
  REWARD_RES(2147483393),
  /**
   * <code>BUY_REQ = 1073741570;</code>
   */
  BUY_REQ(1073741570),
  /**
   * <code>BUY_RES = 2147483394;</code>
   */
  BUY_RES(2147483394),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NONE = 0;</code>
   */
  public static final int NONE_VALUE = 0;
  /**
   * <code>FIRST_PAGE_REQ = 1073741568;</code>
   */
  public static final int FIRST_PAGE_REQ_VALUE = 1073741568;
  /**
   * <code>FIRST_PAGE_RES = 2147483392;</code>
   */
  public static final int FIRST_PAGE_RES_VALUE = 2147483392;
  /**
   * <code>REWARD_REQ = 1073741569;</code>
   */
  public static final int REWARD_REQ_VALUE = 1073741569;
  /**
   * <code>REWARD_RES = 2147483393;</code>
   */
  public static final int REWARD_RES_VALUE = 2147483393;
  /**
   * <code>BUY_REQ = 1073741570;</code>
   */
  public static final int BUY_REQ_VALUE = 1073741570;
  /**
   * <code>BUY_RES = 2147483394;</code>
   */
  public static final int BUY_RES_VALUE = 2147483394;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ProtoCode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ProtoCode forNumber(int value) {
    switch (value) {
      case 0: return NONE;
      case 1073741568: return FIRST_PAGE_REQ;
      case 2147483392: return FIRST_PAGE_RES;
      case 1073741569: return REWARD_REQ;
      case 2147483393: return REWARD_RES;
      case 1073741570: return BUY_REQ;
      case 2147483394: return BUY_RES;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ProtoCode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ProtoCode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ProtoCode>() {
          public ProtoCode findValueByNumber(int number) {
            return ProtoCode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.hk.activity.proto.ActivityProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final ProtoCode[] VALUES = values();

  public static ProtoCode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ProtoCode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:activity.ProtoCode)
}

